### ISSUE TITLE
js based modules dont run

### ISSUE THREAD

**Issue by Ross-Rawlins** [Fedik/FullAJAX#16]
The plugin is amazing but modules that are in the updated content area are not initializing; an example is google charts. do you have a work around for this.

**Comment by Fedik** [comment]
for this no unified way, but you can try like there #7

**Comment by Duovili** [comment]
That doesnt work. My problem is I am running angular in JOOMLA; and my controllers are declared in the AJAX content. Angular works fine but I get problems when trying to run it with your plugin.

**Comment by Fedik** [comment]
I think if you able to use Angular in Joomla then you do not need fullajax plugin :smile: 

you problem can be related to script initialisation, when page reloaded with ajax you need init your scripts manually ... domready not work in this case .. see #7

**Comment by Duovili** [comment]
I tried that but I seem to get more issues when trying to do that with the plugin; I will have to disable the page for now.
