### ISSUE TITLE
multiple module postions

### ISSUE THREAD

**Issue by Duovili** [Fedik/FullAJAX#17]
I wanted to know if you have been able to come up with a work around to update multiple module positions? 

I know I can trick it by loading the extra modules into an article but I am hoping to avoid that.

**Comment by Fedik** [comment]
yes, please look:
https://github.com/Fedik/FullAJAX/wiki/Model2Blocks
and http://getsite.org.ua/en/fullajax/how-to-update-more-than-one-module-with-ajax

not really trivial :wink:

if you asked about joomla plugin, check the plugin configuration there some options, and description with small info "how to" :smile:
